apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: manti-infra
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - name: kibana
      port: 5601
      nodePort: 30110
      targetPort: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kibana
    namespace: manti-infra
    labels:
        app: kibana
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kibana
    template:
        metadata:
            labels:
                app: kibana
            annotations:
                seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
        spec:
            imagePullSecrets: 
              - name: harborsecret
            containers:
              - name: kibana
                image: docker.elastic.co/kibana/kibana-oss:7.4.2
                imagePullPolicy: IfNotPresent
                resources:
                    limits:
                        cpu: 1000m
                    requests:
                        cpu: 100m
                env:
                  - name: ELASTICSEARCH_HOSTS
                    value: http://elasticsearch:9200
                  - name: SERVER_NAME
                    value: kibana
                  - name: SERVER_REWRITEBASEPATH
                    value: "false"
                ports:
                  - containerPort: 5601
                    name: ui
                    protocol: TCP
                livenessProbe:
                    httpGet:
                        path: /api/status
                        port: ui
                    initialDelaySeconds: 5
                    timeoutSeconds: 10
                readinessProbe:
                    httpGet:
                        path: /api/status
                        port: ui
                    initialDelaySeconds: 5
                    timeoutSeconds: 10
