kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      name: rest
      nodePort: 30103
      targetPort: 9200
    - port: 9300
      name: inter-node
      nodePort: 30104
      targetPort: 9300
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: manti-infra
  labels:
    app: elasticsearch
spec:
  replicas: 3
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        securityContext:
          privileged: true
          procMount: Default
          runAsUser: 0
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
        ports:
        - containerPort: 9200 # for REST API.
          name: rest
          protocol: TCP
        - containerPort: 9300 # for inter-node communication.
          name: inter-node
          protocol: TCP
        volumeMounts:
          - name: esdata
            mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: docker-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-0.elasticsearch, es-1.elasticsearch,es-2.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-0,es-1,es-2"
          - name: discovery.type
            value: zen
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
      volumes:
        - name: es-config
          configMap:
            name: es
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: esdata
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: nfs-es
      resources:
        requests:
          storage:  300Mi